### ISSUE TITLE
Recover a block vector from numpy array

### ISSUE THREAD

**Issue by jvellojin** [mathLab/multiphenics#3]
Dear Developers.

I'm trying to define a block vector on Multiphenics with a numpy array (solution vector) by the following code:

`from dolfin import *`
`from multiphenics import *`
`import numpy as np`

`mesh = UnitSquareMesh(2, 2)`

`V = FunctionSpace(mesh, "Lagrange", 2)`
`VV = BlockFunctionSpace([V, V])`

`ran_vec = np.random.randn(VV.dim())`

`u = BlockFunction(VV)`
`u.block_vector().set_local(ran_vec)`

`uu, vv = block_split(u)`
`print(uu.vector().get_local())`
`print(vv.vector().get_local())`

The line `u.block_vector().set_local(ran_vec)` populate u locally, however, when splitting, `uu` and `vv` are just zeros. This approach is the same as FEniCS. What is the proper way to populate `uu` and `vv`?. 

Thanks!

**Comment by francesco-ballarin** [comment]
Add `u.apply("to subfunctions")` after `set_local`.

There is also a `u.apply("from subfunctions")` which would cover the other case: you `set_local` one of the components `uu` and/or `vv`, and force  updating on `u`.

**Comment by jvellojin** [comment]
Thank you, it works as expected.
